### ISSUE TITLE
[feat] Email sending to applicants

### ISSUE THREAD

**Issue by jzeiders** [HackSC/odyssey#122]
We need a way to be able to send emails to people, with segmenetation on properties such as schools or status.

There are 2 ways I can see to do this, we can either use the sendgrid api to import the contacts and send from there. Or add a dashboard to send it from an admin page.

@WilhelmWillie @saresend Thoughts?

**Comment by WilhelmWillie** [comment]
Last year, Daniel built an emailer that used the mail API that Quill used. Worked but lots of engineering effort there

Alternative I was thinking of was to build some admin filter feature that lets us filter users and generate a CSV of relevant users that could be imported and used elsewhere. I think this is a bit safer and requires less engineering effort
