### ISSUE TITLE
[feat][backend] write routes to get statistical point data for houses and individuals

### ISSUE THREAD

**Issue by WilhelmWillie** [HackSC/odyssey#220]
Not sure what this will look like just yet but something like:

* `GET /api/houses` - Returns a JSON object with the house labels and point totals 
* `GET /api/points` - Returns a JSON object of the top 3 users in terms of points, along with the current logged in users point total

**Comment by abigger87** [comment]
I believe @saresend completed houses endpoint for me to sum up on the front end.

- Still need to complete top 3 users
