### ISSUE TITLE
Update Dates on Odyssey with New Timeline

### ISSUE THREAD

**Issue by abigger87** [HackSC/odyssey#363]
If you look on the right hand side of the below picture in the `Major Dates` section, you'll see the application timeline. This needs to be updated. The file this is located in is `/components/steps/Status.tsx`

<img width="1354" alt="Screen Shot 2020-09-17 at 8 15 54 PM" src="https://user-images.githubusercontent.com/21288394/93551527-f1411500-f922-11ea-9af5-8fdf1f2cfcaa.png">

**Comment by jasonsilberman** [comment]
I looked in the Quip, but could not find it. Where can I find the up-to-date deadlines for 2021?

**Comment by abigger87** [comment]
Good question, I just started opening the issues, I think we don't have definitive dates yet. Let's check with @MaxLeiter If he can bring it up with Katie.

**Comment by jasonsilberman** [comment]
Ok sounds good.
