### ISSUE TITLE
Add custom Heroku error page

### ISSUE THREAD

**Issue by MaxLeiter** [HackSC/odyssey#458]
We need a static site hosted on Vercel (or AWS if vercel doesn't work for some reason) to act as a landing page incase the app crashes. It should link to our uptime status and twitter, and apologize for the inconvenience

How to setup / more info: 
https://devcenter.heroku.com/articles/error-pages

**Comment by chloetanlimco** [comment]
Idk if this is exactly what we're looking for, but I wrote up a static error page, added it to a new repo in the hacksc GitHub, and deployed it on Vercel: https://error-seven.vercel.app/error.html

I don't think I have access to heroku, though

**Comment by abigger87** [comment]
Awesome @chloetanlimco that works! Can you also make a similar page for maintenance? Pretty much the same thing just with like "⚠️ site under construction 🛠️ "?

FYI, these pages are pointed to by heroku through a special environment variable that they define, so all i did was set the variables to your URL in the heroku application settings (https://devcenter.heroku.com/articles/error-pages) So when the app goes down or we do emergency maintenance, heroku will forward the site to those URLs

**Comment by abigger87** [comment]
oh and @chloetanlimco just name the page `maintenance.html` if possible, I will preset the environment variables to the url `https://error-seven.vercel.app/maintenance.html`

**Comment by chloetanlimco** [comment]
@abigger87 should be up!

**Comment by abigger87** [comment]
perfect 🤩 gonna go ahead and close this issue. Great job!

also pointed domains `error.hacksc.com` and `maintenance.hacksc.com` to your vercel deployment :)
