### ISSUE TITLE
Fix App Leaderboard

### ISSUE THREAD

**Issue by abigger87** [HackSC/odyssey#501]
- [x] Remove "Needs Bus" from /appLeaderboard - this should be contingent on the `needsBus` constant in https://github.com/HackSC/odyssey/blob/staging/lib/hackathonConstants.ts

- [x] Fix styling on /appLeaderboard

**Comment by MaxLeiter** [comment]
These changes should be conditional on a new `needsBus` constant in https://github.com/HackSC/odyssey/blob/staging/lib/hackathonConstants.ts

**Comment by abigger87** [comment]
Great point! Changing now...
