### ISSUE TITLE
Prevent Accidental Accepts, Waitlists, and Rejects on App Leaderboard Page

### ISSUE THREAD

**Issue by abigger87** [HackSC/odyssey#502]
Maybe its a good idea to tightly restrict access to accepting, waitlisting, and rejecting hackers on /appLeaderboard

Currently, any admin can literally just accept, waitlist, or reject any hacker that has already been reviewed on the /appLeaderboard page:
<img width="1470" alt="Screen Shot 2020-12-19 at 6 20 00 PM" src="https://user-images.githubusercontent.com/21288394/102703019-74258480-421e-11eb-9301-21f2eae5e54d.png">

**Comment by MaxLeiter** [comment]
If announcements are made in the admin visibility slack channel I'm not sure it's worth the effort

**Comment by abigger87** [comment]
Elissa pointed out that it may be clicked by accident though. I think its pretty important - if someone accidentally clicks it's an issue

**Comment by MaxLeiter** [comment]
We can add an 'are you sure' alert?
