### ISSUE TITLE
Remove hackathon constants file and replace usage with admin tool

### ISSUE THREAD

**Issue by MaxLeiter** [HackSC/odyssey#529]
#527 introduced a front-end interface to set hackathon constants, which means we can remove the hardcoded file and convert all usage to the new system. It's not used very much so should be pretty straight forward

**Comment by abigger87** [comment]
I already built this @MaxLeiter its already in prod :/

**Comment by MaxLeiter** [comment]
Yeah I think you missed some instances of hackathonConstants usage though? I might’ve been on the wrong branch when I checked. I reference what you built in the description
