### ISSUE TITLE
[bug] Clicking on logout hangs the application

### ISSUE THREAD

**Issue by saresend** [HackSC/odyssey#59]
```javascript
GET https://odyssey-staging-hacksc.herokuapp.com/_next/static/
JokgKPq1NLFhcXCKtMpzo/pages/auth/logout.js net::ERR_ABORTED 404 (Not Found)
```
Logging out seems to hang, but does successfully logout. If we hit another request or do anything with the page, it does seem to have successfully logged out tho.

**Comment by WilhelmWillie** [comment]
interesting.. looks like its trying to find `/pages/auth/logout` within the next app, whereas /auth/logout should be handled by express/node

**Comment by saresend** [comment]
Yeah, maybe has to do with the actual url path?

**Comment by WilhelmWillie** [comment]
OH wait I know why it is. The navbar uses the default Next.js Link component which tries to client-side route to `/auth/logout` i.e. try to load a Next page, instead of doing an HTTP GET call to /auth/logout

**Comment by saresend** [comment]
One thing thats mega confusing tho is that this seems to work when running on `localhost`

**Comment by WilhelmWillie** [comment]
hmm jk my hunch earlier wasn't it. I tried visiting `/auth/logout` directly via my browser and still ran into issues

**Comment by saresend** [comment]
Can you repro it locally?

**Comment by saresend** [comment]
Wait, this might be an auth0 configuration issue
