### ISSUE TITLE
[bug] status doesn't update properly after application submission

### ISSUE THREAD

**Issue by WilhelmWillie** [HackSC/odyssey#63]

**Comment by WilhelmWillie** [comment]
Ugh this is still happening.

I submitted and had a profile successfully set... but I came back 45 mins later to see that it was reset to verified. Not sure why it would do this, still investigating

**Comment by saresend** [comment]
Yikes, kk lmk if you want more help debugging this

**Comment by saresend** [comment]
Do you have the account email you found this on? Gonna try to check the database to see if the issue is on the data side of things

**Comment by saresend** [comment]
Removing launch blocking label, since it seems like this is hard to repro, and happens very sporadically so it shouldn't affect too many people. We'll fix it live (probably)

**Comment by WilhelmWillie** [comment]
Yeah worst case scenario, we run a script that affects status based on submittedAt

**Comment by saresend** [comment]
Yeah, ideally `submittedAt` becomes our source of truth for whether a user is done w their application, but we can fix that later

**Comment by WilhelmWillie** [comment]
going to put this as closed. we can diagnose this further once we get more data from prod, doesn't seem like we have any problems with losing `submittedAt` data which is the true SoT for whether or not a user submitted anything
