### ISSUE TITLE
[bug] Google auth provider causes 404 failures

### ISSUE THREAD

**Issue by saresend** [HackSC/odyssey#65]
This might be tied with #56, but Google auth provider causes redirection to a `404` Page, rather than the dashboard. The dashboard does however work if you go to it manually. 

## Repro Instructions:

Go to the sign up page in auth0, and sign up with a google account that does not have a preexisting email associated with a HackSC identity. This should get you to the `404`

**Comment by WilhelmWillie** [comment]
i think this is fixed tbh?

**Comment by saresend** [comment]
Yeah, honestly have no idea how to repro this one, and I think it had to do with the missing PK stuff
