### ISSUE TITLE
[bug] resume upload doesn't update resume field in DB

### ISSUE THREAD

**Issue by WilhelmWillie** [HackSC/odyssey#71]

**Comment by saresend** [comment]
## Small investigation things: 

This seems to work on `localhost`. Should probably setup a test env on heroku for running experiments to find bugs that only happen when we're not running locally

**Comment by saresend** [comment]
@WilhelmWillie, in the interest of shipping earlier, thoughts on removing this from launch blocking? Rationale being that it seems like s3 is still getting the resumes, and we can track down who's resume belongs to who based on the fact that the key is the user id in s3, so we can handle this retroactively

**Comment by WilhelmWillie** [comment]
Yeah actually thoughts on updating resume in the /api/resume route anyways?

**Comment by saresend** [comment]
Oh yeah that's way smarter than whatever I was doing lol

**Comment by saresend** [comment]
I'll refactor, in the meantime dropping launch blocking
