### ISSUE TITLE
[feature][large] Affiliate Codes

### ISSUE THREAD

**Issue by jzeiders** [HackSC/odyssey#98]
Let's get the reposting going, want to add affiliate codes so people can help spread the word. Making a full proposal in Quip

**Comment by jzeiders** [comment]
https://quip.com/w5fkACb2sOe0

@WilhelmWillie Take a look and see what you think, I think that affiliate is our best "free" marketing.

**Comment by WilhelmWillie** [comment]
ooh interesting growth hack -- def agree that referrer code is the best way to implement this feature. seems clear to me as to how this would be built out on the backend, guess the biggest question is just where should we include include these in the UI

how i envision it:

- when you finish the application, the results screen will show you a referral code that you can copy, with text encouraging the user to share 
- when you start your application, one of the first sections you see is an optional referrer code field that you can put in 
- on the dashboard, maybe above the dates, you'll see a small section telling you how many ppl have used your referrer code

**Comment by jzeiders** [comment]
Yeah, that's pretty much what I was thinking, I think code creation should be immediate, no reason to prevent someone from sharing.

**Comment by WilhelmWillie** [comment]
fair, i'll think about best ways to split this up. do you think we should prioritize this above any other work atm? most of the ongoing odyssey work is ui/ux improvements

**Comment by jzeiders** [comment]
Lower than the other UX things, I'm going to take a stab at it tonight into tomorrow morning just to prevent it from distracting you. Will send an update around 1 tomorrow.

**Comment by WilhelmWillie** [comment]
sounds good, keep me updated
